export const IMAGES = {
    Logo: require('../assets/images/Logo.png'),
    Calender: require('../assets/images/calender.png'),
    Envelope: require('../assets/images/envelope.png'),
    Phone: require('../assets/images/phone.png'),
    User: require('../assets/images/user.png'),
    Mask: require('../assets/images/mask.png'),
    Eye: require('../assets/images/eye.png'),
    Lock: require('../assets/images/lock.png'),
    DownArrow: require('../assets/images/downArrow.png'),
    LeftArrow: require('../assets/images/leftArrow.png'),
    BottomHome: require('../assets/images/bottomHome.png'),
    BottomProfile: require('../assets/images/bottomProfile.png'),
    BottomCalender: require('../assets/images/bottomCalender.png'),
    BottomTrend: require('../assets/images/bottomTrend.png'),
    Cart: require('../assets/images/cart.png'),
    Location: require('../assets/images/location.png'),
    Notification: require('../assets/images/notification.png'),
    SosAlert: require('../assets/images/sosAlert.png'),
    Add: require('../assets/images/add.png'),
    Search: require('../assets/images/search.png'),
    SearchInsta: require('../assets/images/searchInsta.png'),
    Doctor: require('../assets/images/doctor.png'),
    Pancreatitis: require('../assets/images/pancreatitis.png'),
    Fever: require('../assets/images/fever.png'),
    BloodDrop: require('../assets/images/bloodDrop.png'),
    Thyroid: require('../assets/images/thyroid.png'),
    Urine: require('../assets/images/urine.png'),
    UpArrow: require('../assets/images/upArrow.png'),
    Telescope: require('../assets/images/telescope.png'),
    ProfileImage: require('../assets/images/profileImage.png'),
    Pen: require('../assets/images/pen.png'),
    Settings: require('../assets/images/settings.png'),
    ManageBranch: require('../assets/images/manageBranches.png'),
    ManageMember: require('../assets/images/manageMembers.png'),
    ManageAddress: require('../assets/images/manageAddress.png'),
    AboutUs: require('../assets/images/aboutUs.png'),
    ContactUs: require('../assets/images/contactUs.png'),
    Logout: require('../assets/images/logout.png'),
    UserPen: require('../assets/images/userPen.png'),
    Delete: require('../assets/images/delete.png'),
    Rectangle_1: require('../assets/images/Rectangle1.png'),
    Rectangle_2: require('../assets/images/Rectangle2.png'),
    Rectangle_3: require('../assets/images/Rectangle3.png'),
    Rectangle_4: require('../assets/images/Rectangle4.png'),
    Rectangle_5: require('../assets/images/Rectangle5.png'),
    Rectangle_6: require('../assets/images/Rectangle6.png'),
    Timer: require('../assets/images/timer.png'),
    Calendar: require('../assets/images/calendar1.png'),
    Pdf: require('../assets/images/pdf.png'),
    BookSummary: require('../assets/images/bookSummary.png'),
    Star:require('../assets/images/star.png'),
    bloodDrop:require('../assets/images/bloodDrop.png'),
    blood:require('../assets/images/blood.png'),
    Colon:require('../assets/images/Colon.png'),
    Heart:require('../assets/images/Heart.png'),
    kidney:require('../assets/images/kidney.png'),
    liver:require('../assets/images/liver.png'),
    Lungs:require('../assets/images/Lungs.png'),
    Dr:require('../assets/images/Dr.png'),
    Pancreatitis:require('../assets/images/Pancreatitis.png'),
    Thermometer:require('../assets/images/Thermometer.png'),
    Thyroidtest:require('../assets/images/Thyroidtest.png'),
    Thyroid:require('../assets/images/Thyroid.png'),
    urine:require('../assets/images/urine.png'),
    Bones:require('../assets/images/Bones.png'),
    testtube:require('../assets/images/testtube.png'),
    searchInsta:require('../assets/images/searchInsta.png'),
    ix_ai:require('../assets/images/ix_ai.png'),
    check:require('../assets/images/check.png'),
    water:require('../assets/images/water.png'),
    Tea:require('../assets/images/Tea.png'),
    food:require('../assets/images/food.png'),
    close:require('../assets/images/close.png'),
    Black:require('../assets/images/Black.png'),
    back:require('../assets/images/back.png'),
    remove:require('../assets/images/remove.png'),
    Lab:require('../assets/images/Lab.png'),
    Group:require("../assets/images/Group.png")



}